### ISSUE TITLE
Feature Request: Blacklists

### ISSUE THREAD

**Issue by mtesseracttech** [mcgeer/WastedBankSpace#34] opened 2023-04-06 21:53 UTC
It would be cool if some items could be added to a blacklist, so they don't get marked as wasting bank space. In my experience this can be nice for some items that some players just do not want to keep in their home's storages, like the pyromancer outfit.

**Comment by mcgeer** [comment] 2024-01-27 04:24
Duplicate of #14

**Closed by mcgeer** 2024-01-27 04:24 UTC
